# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
